version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - touch imagedefinitions.json
      - git clone https://github.com/magler/test.git && cd test 
      - GIT_TAG=$(git describe --tag)
      - |
         if [[ "${GIT_TAG}" =~ "demo" ]]; then
           touch imagedefinitions-demo.json;
         fi
artifacts:
  files:
    - imagedefinitions*.json
