version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - CODEBUILD_BUILD_SUCCEEDING=1
      - exit 1
artifacts:
  files: imagedefinitions.json
  name: artifact-${DEPLOYABLE}
