version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - echo '[{"name":"node","imageUri":"node"}]' > imagedefinitions.json
      - git clone https://github.com/magler/test.git && cd test
      - GIT_TAG=$(git describe --tag)
      - echo ${GIT_TAG}
      - |
         if [[ "${GIT_TAG}" =~ "demo" ]]; then
           echo 'Writing demo imagedefinitions-demo.json'
           echo '[{"name":"node","imageUri":"node"}]' > imagedefinitions-demo.json
         fi
      - ls
      - echo 'done'
artifacts:
  files:
    - imagedefinitions*.json
